server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://kkonggi.cnrixypfag42.ap-northeast-2.rds.amazonaws.com/dev?autoReconnect=true # 변경해주세요
    username:  dev # 변경해주세요
    password:  kkonggi_dev07 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전